# Generating a Flake8 report
# Occurring whenever a pull request is made

name: Flaking using flake8

on: pull_request

jobs:
  # This only needs to be run once per pull request
  Flaking:
    # Forcing the use of bash shell if avalible
    defaults:
      run:
        shell: bash
    # Simplest os to run on is ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installing Flake8
        run: |
          pip install flake8

      - name: Run Flake
        run: |
          flake8 src test


